name: Build 2

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      auto_deploy:
        description: Auto deploy to (NONE/UAT)
        default: NONE
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      UAT_REPO_NAME: uat-rail-map-generator

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i

      - name: Clone UAT repo
        run: git clone --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/uat-railmapgen/rmg-repositories.git

      - name: Build
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
        id: build

      - name: Auto deploy
        if: ${{ github.event.inputs.auto_deploy == 'UAT' }}
        run: |
          curl -XPOST -u "wongchito:${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/uat-railmapgen/rmg-repositories/actions/workflows/release.yml/dispatches \
            --data '{"ref": "main", "inputs": {"app_name": "rmg", "version": "${{ steps.build.outputs.RMG_VER }}", "environment": "${{ github.event.inputs.auto_deploy }}"}}'
