name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      UAT_REPO_NAME: uat-rail-map-generator

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci

      - name: Build PRD
        run: |
          npm run build
          git config --global user.name "Build Agent"
          git config --global user.email rmg.build.agent@users.noreply.github.com
          npm version patch -m 'Build RMG version %s'
          echo "RMG_VER=$(echo "console.log(require('./package.json').version)" | node)" >> $GITHUB_ENV
          git push && git push --tags

      - name: Copy PRD Artifacts
        run: |
          git clone --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/wongchito/${{ env.UAT_REPO_NAME }}.git
          mkdir ${{ env.UAT_REPO_NAME }}/$RMG_VER/
          cp -r build/ ${{ env.UAT_REPO_NAME }}/$RMG_VER/PRD/

      - name: Build UAT and Copy Artifacts
        run: |
          echo "var pkg=require('./package.json'); pkg.homepage=\"https://wongchito.github.io/${{ env.UAT_REPO_NAME }}\"; console.log(JSON.stringify(pkg));" | node > package-new.json
          cp package-new.json package.json
          npm run build
          cp -r build/ ${{ env.UAT_REPO_NAME }}/$RMG_VER/UAT/

      - name: Upload Artifacts
        run: |
          cd ${{ env.UAT_REPO_NAME }}/
          git add .
          git commit -m "Build RMG version $RMG_VERSION"
          git push
