name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
      environment:
        description: Environment (UAT/PRD)
        default: UAT
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      UAT_REPO_NAME: uat-rail-map-generator
      PRD_REPO_NAME: RailMapGenerator

    steps:
      - name: Configure Git
        run: |
          git clone --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/wongchito/${{ env.UAT_REPO_NAME }}.git
          git config --global user.name "Release Agent"
          git config --global user.email rmg.release.agent@users.noreply.github.com

      - name: Release to UAT
        if: ${{ github.event.inputs.environment == 'UAT' }}
        run: |
          cd ${{ env.UAT_REPO_NAME }}/
          mkdir GitHub-UAT
          git clone --single-branch --branch master --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/wongchito/wongchito.github.io.git GitHub-UAT/
          rm -r GitHub-UAT/uat-rail-map-generator/*
          cp -r ${{ github.event.inputs.version }}/UAT/ GitHub-UAT/uat-rail-map-generator/
          cd GitHub-UAT/
          git add .
          git commit -m "Release RMG version ${{ github.event.inputs.version }} to UAT"
          git push

      - name: Release to PRD on GitHub Pages
        if: ${{ github.event.inputs.environment == 'PRD' }}
        run: |
          cd ${{ env.UAT_REPO_NAME }}/
          mkdir GitHub-PRD
          git clone --single-branch --branch gh-pages --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/wongchito/${{ env.PRD_REPO_NAME }}.git GitHub-PRD/
          rm -rf GitHub-PRD/*
          cp -r ${{ github.event.inputs.version }}/PRD/* GitHub-PRD/
          cd GitHub-PRD/
          git add .
          git commit -m "Release RMG version ${{ github.event.inputs.version }} to PRD"
          git push

      - name: Release to PRD on GitLab Pages
        if: ${{ github.event.inputs.environment == 'PRD' }}
        run: |
          cd ${{ env.UAT_REPO_NAME }}/
          mkdir GitLab-PRD
          git clone --depth 1 https://chitowong:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/chitowong/${{ env.PRD_REPO_NAME }}.git GitLab-PRD/
          rm -rf GitLab-PRD/*
          cp -r ${{ github.event.inputs.version }}/PRD/ GitLab-PRD/
          cd GitLab-PRD/
          echo "image: node:12.12.0" >> .gitlab-ci.yml
          echo "pages:" >> .gitlab-ci.yml
          echo "  stage: deploy" >> .gitlab-ci.yml
          echo "  script:" >> .gitlab-ci.yml
          echo "    - mv PRD public" >> .gitlab-ci.yml
          echo "  artifacts:" >> .gitlab-ci.yml
          echo "    paths:" >> .gitlab-ci.yml
          echo "      - public" >> .gitlab-ci.yml
          echo "  only:" >> .gitlab-ci.yml
          echo "    - master" >> .gitlab-ci.yml
          git add .
          git commit -m "Release RMG version ${{ github.event.inputs.version }} to PRD"
          git push